### ISSUE TITLE
here you can ask questions

### ISSUE THREAD

**Issue by janboone** [janboone/programming-for-economists#1]
If you have a question, type it here.

Mention whether you are ECO or EBE and the group number for your tutorials.

**Comment by u938877** [comment]
My question is regarding the grading of the datacamp assignments. I actually completed both the  assignments before the deadline, but the table says I failed them.  I received a couple confirmation emails, so I believe something went wrong. 

Could you please check my datacamp registration for me?

**Comment by dennistilburguniversiteit** [comment]
Hello,

I am Dennis van der Heijden an EBE student. (group EBE-01)  
I have a small question about the python exam.
Does it matter what kind of plot I make with matplotlib? I prefer a scatterplot instead of a line chart because the payoff's are not connected. 

Thank you in advance!

**Comment by janboone** [comment]
Hi Dennis,

Scatter plot is fine; whatever you prefer. 

Jan.
