### ISSUE TITLE
my kernel keeps dying

### ISSUE THREAD

**Issue by jesse2212** [janboone/programming-for-economists#100]
"The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened."
this is the message I get

**Comment by janboone** [comment]
do you work on your own computer or on the russet server?

**Comment by jesse2212** [comment]
I forgot I had to work on russet, thnx
