### ISSUE TITLE
plot

### ISSUE THREAD

**Issue by StijnMeijs** [janboone/programming-for-economists#102]
i've putted in: 
y = 3*x+5

but when i want to plot something like this:
plt.scatter(df.y,df.z,)
plt.legend()
plt.xlabel('$y$')
plt.ylabel('$z$')
plt.show()

it keeps saying: 
'DataFrame' object has no attribute 'y'

also for the x and z

**Comment by janboone** [comment]
Indeed, with the code that you give above this is correct. The x and y that you use are not attached to a dataframe. Check the assignments to see how to add columns to a dataframe.
