### ISSUE TITLE
Python: Kernel keeps dying

### ISSUE THREAD

**Issue by helenehulsebosch** [janboone/programming-for-economists#103]
By the Python part of the exam the kernel keeps dying on the jupyter server, I can't even import the usual libraries before I get the announcement that my kennel has died

**Comment by janboone** [comment]
can you give me your u-number, then I will check your notebook

**Comment by helenehulsebosch** [comment]
u555799

**Comment by Juliandeleeuw** [comment]
I've got the same problem with my R exam on the russet server. my u-number is 723989

**Comment by helenehulsebosch** [comment]
Graag! Ik kan nu namelijk geen een van mijn antwoorden runnen en daarbij dus controleren of ze werken

**Comment by janboone** [comment]
I talked to IT, they are solving it. If you need extra time at the end because of this delay, this will be fine. So do not worry.

**Comment by janboone** [comment]
According to IT, it should be solved now. Can you confirm this?

**Comment by Juliandeleeuw** [comment]
Ja hij doet het 👍

**Comment by janboone** [comment]
mooi!

**Comment by helenehulsebosch** [comment]
Bij mij werkt het nog steeds niet, ik krijg geen foutmelding meer maar nu staat er een sterretje op de plek waar een getal moet staan als die is uitgevoerd.

**Comment by helenehulsebosch** [comment]
![image](https://user-images.githubusercontent.com/37596695/45888594-b2713680-bdbe-11e8-9b9b-858613e1637b.png)

**Comment by janboone** [comment]
kun je even uit de notebook gaan en opnieuw proberen? Ik vraag IT wat er is.

**Comment by helenehulsebosch** [comment]
Dan heb ik nog steeds hetzelfde als op de foto

**Comment by janboone** [comment]
Ik hoor van IT dat het nu zou moeten werken. Blijkbaar heb je een aantal (oude) notebooks nog open staan waardoor je geheugen "volloopt".

**Comment by helenehulsebosch** [comment]
Ja hij doet het nu!
