### ISSUE TITLE
uploading github

### ISSUE THREAD

**Issue by teungraat** [janboone/programming-for-economists#105]
I did everything wright when uploading my exams on github. But when I click on the link, I go to the wright page, but then it gives an error: 'Sorry, something went wrong. Reload?'

**Comment by janboone** [comment]
The file is not a jupyter notebook but an html file. Did you work on the russet server?

**Comment by teungraat** [comment]
No I didn't

**Comment by janboone** [comment]
can you email my your python notebook?

**Comment by teungraat** [comment]
I fixed it! thanks for the help
