### ISSUE TITLE
queston g

### ISSUE THREAD

**Issue by Pascalevdven** [janboone/programming-for-economists#108]
From question g) i really don't get the hint : [hint: under a) you have seen the library that contains functions to create a "noisy variable"]
The mean had to be zero, so i don't know what to use from a). 
Don't know if it is possible to get more information?

**Comment by janboone** [comment]
under a) we generate a "noise variable" with has comparable properties

**Comment by Pascalevdven** [comment]
p = np.random.uniform(1,2,size=n_observations)
I guess this formula but changing the 1 of 2 doesn't give me a mean of zero.

**Comment by janboone** [comment]
indeed, when do you have a mean of zero with a uniformly distributed variable? You can also choose another distribution of that is easier...
