### ISSUE TITLE
library(tidyverse)

### ISSUE THREAD

**Issue by StijnMeijs** [janboone/programming-for-economists#109]
it gives me imidiately the error:
NameError                                 Traceback (most recent call last)
<ipython-input-5-9188ef1cfcb1> in <module>()
----> 1 library(tidyverse)

NameError: name 'library' is not defined

**Comment by misjamikkers** [comment]
Do you work in a R notebook?

**Comment by StijnMeijs** [comment]
no in python

**Comment by janboone** [comment]
but "library" is an R command (not python). Can you change the kernel to python?

**Comment by janboone** [comment]
sorry, I mean to R.

**Comment by MateoMalbasic** [comment]
I have the same problem and I cant change it to R

**Comment by janboone** [comment]
what do you mean that you cannot change the kernel to R? Do you work on your laptop or on the russet server?

**Comment by StijnMeijs** [comment]
im working on a computer of the uni, i cannot change it. i can only choose python 3 as a kernel
