### ISSUE TITLE
Assignment week 3 (notebook about game)

### ISSUE THREAD

**Issue by lindaaa1998** [janboone/programming-for-economists#11]
Some other fellow students and me do not really know what is expected from us in the assignment of week 3. If I compare the assignment in Jupyter Notebook and the html-version of the assignment, I can't really see what changes I have to make in the assignment. So the question is what we should do? Which fields do we have to fill in? 

I hope you can help us out (ofcourse not with the answers, but push us in the right direction).

Kind Regards,
Linda Pelzer
Study: EBE
Tutorial Teacher: Jan Boone

**Comment by janboone** [comment]
I am not sure what you mean by "the assignment of week 3". Week 3 was last week and last week's assignment was about your progress on Datacamp. For this week, you need to finish the python course on Datacamp (deadline was yesterday) and make the assignment for week 4 which will be discussed in the tutorial this week. 

For next week (week 5), the assignment is a jupyter notebook (found on [this page](http://janboone.github.io/programming-for-economists/python.html) under week 5. This notebook --with your answers-- has to be uploaded on github before Sunday (April 16) evening 23:59. Then we will grade this notebook.
