### ISSUE TITLE
read.csv

### ISSUE THREAD

**Issue by jesse2212** [janboone/programming-for-economists#111]
![image](https://user-images.githubusercontent.com/37623921/45887933-23175380-bdbd-11e8-940c-3027c41b586c.png)

and the csv is in my c:

**Comment by janboone** [comment]
je werkt op de server, die kent geen "c:/" 

1. upload the csv file op de server
2. als die in dezelfde directory staat als je notebook, kun je ./Medicaid.csv gebruiken.

**Comment by jesse2212** [comment]
i got it

**Comment by misjamikkers** [comment]
The file is not in c: 
Check where Medicaid.csv is
