### ISSUE TITLE
r

### ISSUE THREAD

**Issue by AnoukDeSmet** [janboone/programming-for-economists#112]
Ik krijg het niet voor elkaar om R te downloaden in de russet.uvt.nl -> als ik hem zelf upload krijg ik niet de pagina waar ik zelf alles in kan vullen en ik weet niet meer hoe ik het kan oplossen

**Comment by janboone** [comment]
R downloaden? Wat bedoel je precies?

**Comment by AnoukDeSmet** [comment]
![image](https://user-images.githubusercontent.com/37408583/45888290-ff084200-bdbd-11e8-9789-8f5944187627.png)

ik krijg dit zodra ik het r tentamen in russet download

**Comment by AnoukDeSmet** [comment]
Ik heb het via de announcement gedownload, maar hij kwam niet vanzelf tevoorschijn

**Comment by janboone** [comment]
voor de russet server heb je de ipynb file nodig (niet de Rmd file)
