### ISSUE TITLE
Question E, Python

### ISSUE THREAD

**Issue by julianlo14** [janboone/programming-for-economists#113]
When I submitted my answer voor question e of python i got this:

/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "

**Comment by janboone** [comment]
Does it still work? (it is only a warning).

If you want to get rid of the warning, use "density=True"
