### ISSUE TITLE
creating a new variable

### ISSUE THREAD

**Issue by Mcococh** [janboone/programming-for-economists#117]
Error in combine_vars(vars, ind_list): Position must be between 0 and n
Traceback:

1. medicaid1 %>% select(Recipients_N)
2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
3. eval(quote(`_fseq`(`_lhs`)), env, env)
4. eval(expr, envir, enclos)
5. `_fseq`(`_lhs`)
6. freduce(value, `_function_list`)
7. withVisible(function_list[[k]](value))
8. function_list[[k]](value)
9. select(., Recipients_N)
10. select.data.frame(., Recipients_N)
11. select_vars(names(.data), !(!(!quos(...))))
12. combine_vars(vars, ind_list)
is what i get when i try to progrAM THIS:
library(dplyr)
Total_Costs <- medicaid1 %>%
                  select(Total_costs)

Recipients_N <- medicaid1 %>%
                  select(Recipients_N)

Costs_per_Recipient <- Total_Costs/Recipients_N
Could you please help me?

**Comment by misjamikkers** [comment]
You should create a new variable Cost_per_Recipient with dplyr
