### ISSUE TITLE
Can't read in a file

### ISSUE THREAD

**Issue by Luuk1998** [janboone/programming-for-economists#119]
I can't read in my Medicaid.csv, every time i got the error 'Warning message in file(file, "rt"):
"cannot open file '../Medicaid (2).csv': No such file or directory" What can I do?

**Comment by janboone** [comment]
in what directory did you save this file? Are you working on your own computer or the russet server?

**Comment by Luuk1998** [comment]
I'm working on my own computer, i tried downloads and documents

**Comment by janboone** [comment]
If the file is in Downloads, "/Downloads" should be in the path somewhere. Or is the csv file in the same directory as the notebook?

**Comment by Luuk1998** [comment]
What do you mean by path?

**Comment by janboone** [comment]
are you working on a mac or windows?

**Comment by Luuk1998** [comment]
WIndows

**Comment by Luuk1998** [comment]
Do I need to set it in a folder?

**Comment by Luuk1998** [comment]
It works, thank you
