### ISSUE TITLE
cant read medicaid

### ISSUE THREAD

**Issue by StijnMeijs** [janboone/programming-for-economists#123]
it just keeps saying that is isn't there

**Comment by janboone** [comment]
can you send a screenshot?

**Comment by misjamikkers** [comment]
Check where the csv is

**Comment by StijnMeijs** [comment]
![image](https://user-images.githubusercontent.com/37622490/45890721-f1ee5180-bdc3-11e8-9d5b-765e2935c9d6.png)

**Comment by StijnMeijs** [comment]
![image](https://user-images.githubusercontent.com/37622490/45890798-1a764b80-bdc4-11e8-8602-e456c8288787.png)

**Comment by janboone** [comment]
perhaps "./Sourcedata/Medicaid.csv" works? I.e. only one "." (not "..")

**Comment by StijnMeijs** [comment]
yes it does, thank you so much!!
