### ISSUE TITLE
uploading files

### ISSUE THREAD

**Issue by c4milla** [janboone/programming-for-economists#128]
I have uploaded my files correctly (I think). however, I can't open them through the like, it keeps saying that something went wrong. Do you have any idea why that is? Because now I don't know if I actually uploaded the right files properly.

**Comment by c4milla** [comment]
it seems to have fixed itself. Struggled with it for 20 minutes and decided to make an issue, 2 minutes later it works.

Thanks anyways

**Comment by janboone** [comment]
indeed I can read them.
