### ISSUE TITLE
question about enrolling in Datacamp

### ISSUE THREAD

**Issue by teunvisser** [janboone/programming-for-economists#13]
I noticed that i didn't enroll into the DataCamp group. I can participate in the normal free courses like Python for beginners but i'm not part  of the group for you to see my progress. This is likely due to the fact that i registered incorrectly for the webform. I hope there is a solution for this problem.

Thank you in advance,

Teun Visser ECO-03 (413508)

**Comment by janboone** [comment]
I've sent you an invitation to join the group as you will need this for the R-part of the course.
