### ISSUE TITLE
problems uploading both exams

### ISSUE THREAD

**Issue by Kiewit** [janboone/programming-for-economists#133]
in the case of the python exam it constantly showed "Sorry, something went wrong. Reload?" when I tried to see if the upload had succesfully occured

in the case of the R exam I tried to make it into an HTML file and upload it but that only results in nigh unreadable code

**Comment by jespervandoorn** [comment]
I have the same problem

**Comment by janboone** [comment]
file looks fine to me, there seem to be some wife problems when everyone is uploading
