### ISSUE TITLE
How to upload R Exam from R studio

### ISSUE THREAD

**Issue by Kiewit** [janboone/programming-for-economists#136]
I tried to upload the R exam using the knit function by to turn it into an HTML file but then I just get this code. What exactly am I doing wrong here?

![afbeelding](https://user-images.githubusercontent.com/37505140/45892375-3bd93680-bdc8-11e8-84b8-254e97038a03.png)

**Comment by misjamikkers** [comment]
This is ok.

**Comment by Kiewit** [comment]
okay then I shall leave it as is

thank you
