### ISSUE TITLE
Mixed up Python and R in readme

### ISSUE THREAD

**Issue by Cvanwanrooij** [janboone/programming-for-economists#139]
Name: Cascha van Wanrooij, 2014934, EBE

During the exam there was an issue where uploading the exam files to github took unreasonably long. I managed to upload the files in time however I couldn't view them yet and so I accidentally mixed up the R and Python hyperlinks in Readme. So the R hyperlink links to python and the python hyperlink links to R.

I can't modify the readme for obvious reasons, so I hope you're willing to look past this. Sorry for the inconvenience.

**Comment by misjamikkers** [comment]
We will check this.

**Comment by janboone** [comment]
python file looks fine.
