### ISSUE TITLE
Exam R Question 2

### ISSUE THREAD

**Issue by MarienvanLoon** [janboone/programming-for-economists#140]
Hello,

I have a question about the second assignment in the R exam. You asked to create the new variable Cost_per_Recipient what means that you need to divide the variable Total_Costs" by the variable "Recipient according to the assignment.

I struggled with this problem for a hour, I guess, because the variable Total_Cost could not be found.
After the exam I heard that the variable Total_Cost, as written in the question, not existed but that it was the variable Total_cost without a capital C.

In my exam I have a code that normally works ( I tested if it works when I changed the C in a c) only I have Total_Cost as variable caused by the reason I mentioned before and not the variable Total_cost. That is the reason why the code didn't create a new variable.

Of course I get that I receive no points for assignment 3, but is there a chance that I receive points for assignment 2?

Thank You

**Comment by misjamikkers** [comment]
I have send you an email.
