### ISSUE TITLE
finding files

### ISSUE THREAD

**Issue by nicvdv** [janboone/programming-for-economists#141]
i saved all the files on my computer by documents in a map. But i cant find them in jupiyter now. How is that possible

**Comment by nicvdv** [comment]
on the computer from the university

**Comment by janboone** [comment]
can you locate the downloads using windows explorer?

**Comment by nicvdv** [comment]
its in a folder under my documents. but in jupyter i cant find it

**Comment by nicvdv** [comment]
im now trying it with the russet server but still cant find it

**Comment by janboone** [comment]
can you ask one of the student assistants to help you?

**Comment by misjamikkers** [comment]
Which room are you in?
