### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by EmmekePleging** [janboone/programming-for-economists#143]
![error](https://user-images.githubusercontent.com/37622167/47563425-14730d80-d922-11e8-8983-f0e8e4b20a54.png)
Hi, I dont understand why this is an error

**Comment by janboone** [comment]
that looks indeed odd. Are you working in your laptop or the russet server?

**Comment by EmmekePleging** [comment]
russet server

**Comment by janboone** [comment]
can you give me your u-number, then I can check

**Comment by EmmekePleging** [comment]
u247345

**Comment by janboone** [comment]
is that your u-number? I cannot see you on the server.

**Comment by janboone** [comment]
Sorry, I can see you now. But the code runs normally. Has this been solved?

**Comment by EmmekePleging** [comment]
oh im working on the russet server on my laptop because it did not work like it usually does on my laptop

**Comment by EmmekePleging** [comment]
i switch x_range and range_x but i don't know if thats correct. it does work right now.

**Comment by janboone** [comment]
great that it works!
