### ISSUE TITLE
For question e on phyton, I have the correct code by I keep getting an error

### ISSUE THREAD

**Issue by kevinn12** [janboone/programming-for-economists#144]
root = optimize.fsolve(f, [-1.5,-0.5,1,1.5]) 

print(root)

**Comment by kevinn12** [comment]
TypeError: 'int' object is not callable

**Comment by janboone** [comment]
are you working on the russet server so that I can check what you have done?

**Comment by kevinn12** [comment]
Yes! u422136

**Comment by janboone** [comment]
your choice of initial guess 1 is perhaps not ideal...
