### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KoenJoosten19** [janboone/programming-for-economists#149]
On the python exam question c) I have put in print(optimize.fmin(f,-2)), but I get an error.

**Comment by KoenJoosten19** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-65-0c72c50747b8> in <module>()
----> 1 print(optimize.fmin(f,-2))

/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py in fmin(func, x0, args, xtol, ftol, maxiter, maxfun, full_output, disp, retall, callback, initial_simplex)
    406             'initial_simplex': initial_simplex}
    407 
--> 408     res = _minimize_neldermead(func, x0, args, callback=callback, **opts)
    409     if full_output:
    410         retlist = res['x'], res['fun'], res['nit'], res['nfev'], res['status']

/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py in _minimize_neldermead(func, x0, args, callback, maxiter, maxfev, disp, return_all, initial_simplex, xatol, fatol, **unknown_options)
    530 
    531     for k in range(N + 1):
--> 532         fsim[k] = func(sim[k])
    533 
    534     ind = numpy.argsort(fsim)

ValueError: setting an array element with a sequence.

**Comment by janboone** [comment]
what does your function f look like?
