### ISSUE TITLE
Problem with Assingment week 6, excel

### ISSUE THREAD

**Issue by SuzannePluym** [janboone/programming-for-economists#15]
I am an EBE student from group 1EBE-01. I have a problem with the assignment for week 6. When I type "library(readxl)" in a cell and press shift + enter, it gives the following error:
NameError: name 'library' is not defined. 
I believe I can't move on with the assignment if I get this error, so I would like to know how to solve this problem. I tried Googling it but couldn't find anyting useful.
Thank you in advance.

**Comment by sbohorquez** [comment]
Hi Suzanne, 
You're probably not using the R kernel, go to kernel and choose R, if this option is not there it means you need to install it, in that case open a command prompt and type: conda install -c r r-essentials
After it installs you should be able to use the R kernel.
