### ISSUE TITLE
Datacamp assignments

### ISSUE THREAD

**Issue by u938877** [janboone/programming-for-economists#17]
My question is regarding the grading of the datacamp assignments. I actually completed both the assignments before the deadline, but the table says I failed them. I received a couple confirmation emails, so I believe something went wrong.

Could you please check my datacamp registration for me?

Kind regards
Duane Sluer,
EBE-08

**Comment by janboone** [comment]
I cannot find a dcsluer account on datacamp. Which account do you use?

**Comment by u938877** [comment]
I created my account using my tilburg university google account. 

 d.c.sluer@tilburguniversity.edu

But my profile name should be dcsluer.

**Comment by janboone** [comment]
I have sent a new invitation

**Comment by u938877** [comment]
I clicked on it, did it work ?

**Comment by janboone** [comment]
indeed, you now have two passes for the datacamp assignments.
