### ISSUE TITLE
Question about assigment week 6

### ISSUE THREAD

**Issue by XavieraSpanhaak** [janboone/programming-for-economists#18]
Hi,
If I put this s<-read.cvs('Salaries.cvs', 1) print(s) in a cell and I press shift+ enter I get the following error: Error in eval(expr, envir, enclos): could not find function "read.cvs".
I tried to google the error but I couldn't find anything. 
How can I solve this problem?

Greetings,
Xaviera Spanhaak
EBE-08

**Comment by misjamikkers** [comment]
Hi Xaviera,

You seemed to have made a typo. The documenttype is "csv" and not "cvs".

Misja
