### ISSUE TITLE
Problem with datacamp account

### ISSUE THREAD

**Issue by tfurrer98** [janboone/programming-for-economists#19]
Hi! I got a problem with my data camp pass/fail grades. I completed them on time but I got a -1 on both of them. Also, I can't continue with the dplyr course, because I don't have a premium datacamp account, apparently. I used the following e-mail adres: t.h.furrer@uvt.nl. 
I also got a -1 for my jupyter notebook assignment for week 5, so i'm also concerned that there is a problem there. 
I hope this can be fixed.

Tim Furrer, first year EBE student
SNR: 2003236
ANR: 532447

**Comment by janboone** [comment]
I invited you for datacamp and your datacamp assignments are fine. I cannot find the week 5 assignment on your github account. So that remains a fail.
