### ISSUE TITLE
problem with IRkernel on jupyter notebook

### ISSUE THREAD

**Issue by Thomasso98** [janboone/programming-for-economists#20]
hello,
the first time i had to do an assignment in R i had problems with the kernel, but i finally downloaded it via github. i found there the code i run in a R console; install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
devtools::install_github('IRkernel/IRkernel') like this and then i run IRkernel::installspec() and IRkernel::installspec(user = FALSE) in a r console. back then it was fixed so i was ready to go, but now when i wanted to do assignment 5 it didnt work anymore. in my jupyter notebook it says that the kernel is dead and that there is no kernel found. so i did the same as i did the first thime, with the codes in a r console, but now that doesnt work either. in the lecture on monday i was told that i had to install anaconda again or install miniconda. i did both and the kernel still doesn't work. i have searched over the whole internet but can't fix the problem. so what can i do to make the irkernel work again?
greets Thomas van den Heuvel

EBE student
teacher is C. Fiedler

**Comment by clemensfiedler** [comment]
Hi Thomas,

To clarify: the error still reads that the r kernel is dead? Could you let me know what the terminal (opdracht promp) reads?

**Comment by Thomasso98** [comment]
[I 14:45:09.053 NotebookApp] Kernel started: 118e6ddd-97cd-4316-bb54-99d6e2b9f49e
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[W 14:45:19.143 NotebookApp] Timeout waiting for kernel_info reply from 118e6ddd-97cd-4316-bb54-99d6e2b9f49e
[I 14:45:21.132 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 118e6ddd-97cd-4316-bb54-99d6e2b9f49e restarted
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[W 14:45:24.178 NotebookApp] KernelRestarter: restart failed
[W 14:45:24.179 NotebookApp] Kernel 118e6ddd-97cd-4316-bb54-99d6e2b9f49e died, removing from map.
ERROR:root:kernel 118e6ddd-97cd-4316-bb54-99d6e2b9f49e restarted failed!
[W 14:45:24.211 NotebookApp] Kernel deleted before session
[W 14:45:24.212 NotebookApp] 410 DELETE /api/sessions/3aedd1fb-2bdb-43ba-93c4-13d435b6be41 (::1) 2.00ms referer=http://localhost:8888/notebooks/Downloads/assignment5.ipynb

**Comment by clemensfiedler** [comment]
We are still looking into that problem. In case Jupyter for R doesn't work in time for the take-home exam you may use R-Studio.

**Comment by Thomasso98** [comment]
Do I have to upload the script made in R-studio or just the codes in the original assignment file without running them, like I did with assignment 5?

**Comment by clemensfiedler** [comment]
You will be provided with an R Markdown document. It can do pretty much what Jupyter (it uses basically the same syntax) you can produce a document with graphs, results etc.

**Comment by janboone** [comment]
Just to be clear:

* install R via: http://cran.xl-mirror.nl/
* install R-studio: https://www.rstudio.com/products/rstudio/download/
* once the final assignments are posted on BB, email Misja to get the R-studio version of the R assignment
* the python assignment is done in the jupyter notebook

Alternatively, do the assignment on one of the computers on campus
