### ISSUE TITLE
Question about final assignment

### ISSUE THREAD

**Issue by lindaaa1998** [janboone/programming-for-economists#21]
I am an EBE-student and I have a question about the final assignment. I have used several times my ANR number instead of my SNR number, but in the pass/fail-grade sheet, my SNR number is used. My question is if I have to use my ANR or SNR number for the final assignment, because I gave my ANR number several times in the assignments and in the sheet is my SNR number. Thank you in advance!

**Comment by janboone** [comment]
use the number that is in the pass/fail-grade sheet.
