### ISSUE TITLE
Exam Question

### ISSUE THREAD

**Issue by TomMeeuwissen** [janboone/programming-for-economists#22]
Hello,

I have a few question about the R exam. 

1. I have to make a line graph and it states the following: "Then, make a line graph with "Year"  and "Cost" on the y-axis."
I assume that there is a typo and that Year has to be on the x-axis? If this is not the case then I have to look further.

2. The last question asks me to make a bar chart of the efficiency scores. I was almost done with it when I found out that my bar chart is exactly the opposite of the one you need to get. This is due to the Ratio term which has to be between 0 and 1. But if you devide Cost by LE, you get an Ratio of 12 and higher and if you then divide all Ratios by the lowest Ratio you'll get values greater than 1. 
I don't know what to do about this. Is there something I missed? 
Thank you in advance.

Tom

**Comment by misjamikkers** [comment]
Hi Tom,

Thanks for your mail.

1. You are right: you should read: Year on the x-axis and Cost on the y-axis.

2. Again you are right:

The efficiency scores should be computed in 2 steps
A: first make ratio as Cost/LE (this need not to be 0 < Ratio < 1
B: then make Score as the minimum Ratio divided by Ratio (and there 0 < Score <= 1)

So in your words:
You should have the lowest ratio divided by the ratio 

It seems you will be all right with the exam!
Success!

Misja

Verstuurd vanaf mijn iPad

**Comment by lindaaa1998** [comment]
Hello,
The assignment said that the Score have to be calculated differently:
"Create a new column called "Score" with mutate. Score is the ratio per country divided by the lowest ratio in the dataframe. ". If it is lowest ratio divided by country, than it needs to be adjusted.

Linda Pelzer, EBE-student.
