### ISSUE TITLE
Final Assignment Question

### ISSUE THREAD

**Issue by moraesmark** [janboone/programming-for-economists#23]
Dear Professor, 

I noticed a possible issue within the R exam file:
In the last question that asks us to make a bar chart with the efficient scores, my output of the bar chart looks the opposite of the example chart, which upon closer inspection was due to the ratio value which is supposed to be between 0 and 1. However, the question states that after you determine Ratio by dividing Cost by LE, then dividing all the ratios by the lowest ratio, the output of this ratio test is greater than 1. 

So would it be correct to assume, that we need to divide lowest ratio by Ratio to replicate the example output?

Thank You,

Mark

**Comment by misjamikkers** [comment]
Dear Mark,

Thank you for your email. You are right. The correct text should be:

Select all the variables except the NA's (hint: use na.omit) and create a new column called "Ratio" with mutate. Ratio is defined as "Cost/LE" (cost per output).
Create a new column called "Score" with mutate. Score is the lowest ratio in the dataframe divided by the ratio per country.
To complete this dataframe order the dataset using "arrange" based on score (i.e. lowest Score first).

Success with your exam!
Misja
