### ISSUE TITLE
Problem with Final Python Assignment

### ISSUE THREAD

**Issue by lindaaa1998** [janboone/programming-for-economists#25]
Hello,

I am working on question 6 in my final Python assignment and I keep getting an error. First the error "your_offer is not defined" was given, so I changed in question 4: **return** your_offer,your_profit,other_profit in **return** offer[n-1] but than I get an Keyerror as follow: 
---> 5 return offer[n-1]
KeyError: 0

Hopefully you can help me out here. 

Linda Pelzer, EBE-student

**Comment by janboone** [comment]
Hi Linda,

Can you email me your notebook? 

Regards,

Jan.

**Comment by lindaaa1998** [comment]
Hello Jan,

The Keyerror pops up in question 6, but it refers to a problem in question
4. I hope you can help me with this.

Regards,

Linda Pelzer, EBE-student
