### ISSUE TITLE
Vagueness about the resit

### ISSUE THREAD

**Issue by BartvanVlijmen** [janboone/programming-for-economists#26]
Hello,

i got some questions about the deadlines and the possible resit. Because now you can choose of two deadlines; the regular one of 7 july or the earlier one of 13 june. But is there a deadline and when would that be? For example, if someone hands in his/her work before the deadline of 7 july and he failed, when would the resit be (if there is one)? The same if the student hands in his/her work before the deadline of 13 june?

Hopefully you could explain a bit more about the resit.

With kind regards,

Bart van Vlijmen

**Comment by janboone** [comment]
The deadline for the exam is June 13 (yesterday). The deadline for the resit is July 7.

Does this help?
