### ISSUE TITLE
Programming Grade

### ISSUE THREAD

**Issue by NoutHakkesteegt** [janboone/programming-for-economists#27]
Hello,

I submitted my final assignment before the deadline of June 13th. I submitted this at the same time as my working partner however he has already received his grade but i haven't i also talked to my other course mates and they have all received their grades all ready while i have not. I was wondering whether i had submitted everything correctly or if there was some other issue? hopefully it can be resolved quickly, thank you in advance.

Kind Regards,
Nout Hakkesteegt

**Comment by sbohorquez** [comment]
Hi Nout,

I checked and your exam was graded along with everyone else that submitted. What do you mean by, you haven't received your grade?

Best,
Santiago Bohorquez

**Comment by NoutHakkesteegt** [comment]
Hello Santiago,

Then it is probably my bad. However i am unable to find my grade on blackboard, which is why i was getting worried.

Kind Regards,
Nout Hakkesteegt

**Comment by janboone** [comment]
Hi Nout,

Indeed, you have the max grade, so there is nothing to worry about. 

I am not sure what went wrong here. I will add your grade to the file with resit-grades. So you should receive it then (and hopefully earlier).

Does that work?

Regards,

Jan.

**Comment by NoutHakkesteegt** [comment]
Hello Jan,

That will work, thank you very much for resolving the problem!

Kind Regards,
Nout Hakkesteegt
