### ISSUE TITLE
Yet to receive grade

### ISSUE THREAD

**Issue by TRuijgers** [janboone/programming-for-economists#28]
Hello,

I uploaded my final assignment a few minutes before the deadline on the 13th of June and filled in the google form, but I have yet to receive my grade. I would really like to know my grade so I can decide if I want to take the resit or not.

My problem seems to be similar to [another issue](https://github.com/janboone/programming-for-economists/issues/27) that was raised a few days ago.

Yours faithfully,

Thomas Ruijgers.

**Comment by janboone** [comment]
Hi Thomas,

No need to do the resit; you cannot get a higher grade...

Can you send me --by email-- your snr (you gave us your anr); then I will add your grade to the resit grades that we send to the exam office.

Regards,

Jan.
