### ISSUE TITLE
Grades for the earlier assignment

### ISSUE THREAD

**Issue by InMyLife** [janboone/programming-for-economists#29]
Hi, 

I've made the final assignment before  June 13, however I haven't recieved a grade yet. The pdf file which is supposed to hold all the final grades only shows the grades up until the first 2,5 points. I'm not able to tell if I have passed or if I have to redo the exam before July 7th...

**Comment by janboone** [comment]
I reported your grade to the exam office. Can you send me by email your SNR (just to be sure). Then I will send them your grade again.

There is no need for you to do the resit; you won't get a higher grade...

Regards,

Jan.
