### ISSUE TITLE
Collecting GitHub account names

### ISSUE THREAD

**Issue by MarcusKlik** [janboone/programming-for-economists#3]
Hi @janboone , from the course website I see that you are collecting students GitHub account names with a Google Docs web form. Does that mean that you have an easy method of compiling a list of account names for a small demo analysis of GitHub commits? 
(nicely done website by the way, did you compile it with a Python tool?)

**Comment by janboone** [comment]
Indeed, the python tool that I use for the website is this one: http://www.sphinx-doc.org/en/stable/
