### ISSUE TITLE
Datacamp invitation 

### ISSUE THREAD

**Issue by Maevezw** [janboone/programming-for-economists#31]
Hello,

Because I'm not part of the 'programming for economists' group, I can't continue my datacamp assignment of week 3. For some reason I thought I accepted the invitation, because Datacamp said so, but during the assignment I got a notification that I only could continue if I would buy a package on Datacamp. I don't know if this is my own fault, because I filled in the online form with my tilburg university adress, and I am using my tilburg university adress on datacamp. I also never received an email with an invitation to this group.

What can I do to solve this?

Kind regards, 
Maeve Zweers, EBE-student

**Comment by janboone** [comment]
Indeed, you are a member of the group. Sometimes it helps to log out of Datacamp and then log in again.
