### ISSUE TITLE
Datacamp registration problem

### ISSUE THREAD

**Issue by SamHamers** [janboone/programming-for-economists#33]
Hello I'm Sam Hamers, EBE student from group 1EBE-05. I just saw the file with the Python grades and noticed I had a 0 for the Datacamp assignments although I did all the assignments in time. Then I saw that I was also on the list of e-mail addresses that still had to register to Datacamp. The Tilburg University e-mail adress in this list is exactly the same as the one I use to make the assignments on Datacamp and I've also been part of the 'programming for economists' group since the start of this course. 

Did something go wrong in the signing up process? Is there any way I can fix this problem?

**Comment by KRoeling** [comment]
Hello, I am Kiki Roeling, EBE student from groep 1EBE-06. I have exactly the same problem and I would also like to know how to fix this.

**Comment by janboone** [comment]
both of you were registered twice. I have corrected this now.

**Comment by KRoeling** [comment]
So will we get the points for Datacamp now?

**Comment by janboone** [comment]
indeed you have.
