### ISSUE TITLE
Collaboration on final assignment.

### ISSUE THREAD

**Issue by Cvanwanrooij** [janboone/programming-for-economists#35]
Hello I'm Cascha van Wanrooij, EBE student from group 1EBE-06. I was wondering if you were allowed to collaborate with another EBE student from a different tutorial group. According to the blackboard announcement 'you are allowed to do these final assignments together with one other student'. However Github reports: 'The final assignment, like the other assignments, you can do together with one other student from the same tutorial group as yours.'

Thanks in advance,

Cascha

**Comment by janboone** [comment]
For the exam you can also collaborate with someone from a different tutorial group. Make sure that both of you upload the exam on your github page and both fill in the google form.
