### ISSUE TITLE
DENOMINATIE

### ISSUE THREAD

**Issue by Hwouters1997** [janboone/programming-for-economists#37]
I cannot find the column DENOMINATIE in the csv files.

**Comment by sbohorquez** [comment]
It's a variable in the 'schools.csv' file, which you are asked to load in question 2di.

**Comment by Hwouters1997** [comment]
It is when I open schools.csv in excel but it isn't available when i read the schools.csv in russet. I used Head on schools to see what variables it contains.

**Comment by sbohorquez** [comment]
because the dataset contains a lot of variables some of them may not appear when you use head, use names(schools) to see all the names of the variables in the dataset. If you correctly load the data DENOMINATIE should appear
