### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by MaudRutten** [janboone/programming-for-economists#38]
Hallo,
Ik krijg steeds een error bij het laden van de Packages: Error in library(thematicmaps): there is no package called 'thematicmaps'.
Terwijl ik wel alle bestanden heb gedownload. Ik kan dus zo niet verder met mijn assignment.
Groetjes Maud

**Comment by misjamikkers** [comment]
Hoi Maud,

Als het goed is heb je het package voor week 6 geinstalleerd.

De code was:
`install.packages("../Package//thematicmaps_2.1.tar.gz", repos = NULL, type = "source")`

Om de code te kunnen runnen is het belangrijk dat je 
1. je code in bepaalde folder hebt opgeslagen (in de cursus deden we steeds de folder "Code".
2. Dat je zip-file download en in de  folder "Package" op gelijk niveau als code opslaat.

Dus code leest als volgt
`.. `     betekent "Ga een folder omhoog"
`/Package`   "Ga naar de folder Package"

Misja

**Comment by BornaMD** [comment]
Waar moet je dit runnen?
