### ISSUE TITLE
thematicmaps not available?

### ISSUE THREAD

**Issue by Dubbeldip** [janboone/programming-for-economists#39]
Hi,

I am trying to use thematicmaps, but it keeps saying: 

_Error in library(thematicmaps): there is no package called 'thematicmaps'
Traceback:

1. library(thematicmaps)
2. stop(txt, domain = NA)_

I also tried to install it multiple times but when I i do it gives me the following error: Warning message:
_"package 'thematicmaps' is not available (for R version 3.4.3)"_

Is there a way to solve this?

**Comment by misjamikkers** [comment]
You have to follow the instructions from week 6 in the notebook maps.

Steps are:
1 Create folders Code and Package
2. Save your notebook in the folder code
3. Download the package (https://janboone.github.io/programming-for-economists/R.html#week6) as a zip file
4. Save the zip file in the folder "Package"
5. Run `install.packages("../Package//thematicmaps_2.1.tar.gz", repos = NULL, type = "source")` in your notebook

Then it should work
Misja
