### ISSUE TITLE
Load error Anaconda install

### ISSUE THREAD

**Issue by XavieraSpanhaak** [janboone/programming-for-economists#4]
Hi,
Everytime I try to  put 'conda install -c r r-essentials' in the 'opdrachtpromt'. I get an error. Which is the following: Load error: in C:\Users\Xaviera\.condarc on line 5, column 0. Invalid YAML. I already reinstalled Anaconda. But I still get the error. Jupyter notebook does work. How can this be solved? 

Greetings,
Xaviera Spanhaak
EBE-08

**Comment by janboone** [comment]
Hi Xaviera,

Indeed, I have seen this error before and it is easy to solve. You need to change something in the file .condarc. Can you open this file? (this is not straightforward as the file is "hidden")

If you cannot open the file, could you join my tutorial next week (Wednesday, 12:45 in AZ 019)? Then I will solve it for you (assuming you have a laptop)

Regards,

Jan.

**Comment by clemensfiedler** [comment]
To fix this error you have to open the following file in notebook
`c:\users\<your username>\.condarc`
for you this would be:
`c:\Users\Xaviera\.condarc`
note that the file is hidden so you have to change the settings of windows to diplay hidden files

the file should only contain 3 lines:
```
channels:
  - anaconda-fusion
  - defaults
```

delete the rest.
