### ISSUE TITLE
thematicmaps doesn't load...

### ISSUE THREAD

**Issue by Anthonyvandenberg** [janboone/programming-for-economists#43]
I tried to load thematicmaps, but I got the following error:

Error in library(thematicmaps): there is no package called 'thematicmaps'
Traceback:

1. library(thematicmaps)
2. stop(txt, domain = NA)

So I tried to install it again with:

install.packages("../Package//thematicmaps_2.1.tar.gz", repos = NULL, type = "source")

but i got an error saying that "installation of package '../Package//thematicmaps_2.1.tar.gz' had non-zero exit status"...

**Comment by sbohorquez** [comment]
see @misjamikkers answer to issue #39
