### ISSUE TITLE
school.csv

### ISSUE THREAD

**Issue by JimvandenBerg** [janboone/programming-for-economists#44]
every time i download school.csv it gives an error.
What can i do about it?

**Comment by clemensfiedler** [comment]
Can you post the error message/describe the error?

**Comment by JimvandenBerg** [comment]
http://localhost:8888/edit/Downloads/schools.csv

Error! C:\Users\Jim\Downloads\schools.csv is not UTF-8 encoded
Saving disabled.
See Console for more details

**Comment by clemensfiedler** [comment]
So you downloaded the file and get the error when opening it with the notebook? Or do you get the error when importing it into R?

- download the file again from blackboard
- if this does not help: check if you can open the file in a text editor (e.g. notebook) 
  - if not post here
  - if yes, does it look normal (commas and text, no weird symbols) if not can you post the first line here?

**Comment by clemensfiedler** [comment]
sent csv file via email. 

try: read.csv2(...) or read.csv2(..., fileEncoding = "UTF-8")

**Comment by JimvandenBerg** [comment]
it won't support the file

**Comment by clemensfiedler** [comment]
@misjamikkers any ideas?

**Comment by JimvandenBerg** [comment]
i think it is fixed
