### ISSUE TITLE
there is no package called 'thematicmaps'

### ISSUE THREAD

**Issue by IvovanZitteren** [janboone/programming-for-economists#47]
I already downloaded the files from week 6 and I typed install.packages("../downloads//thematicmaps_2.1.tar.gz", repos = NULL, type = "source") in the assignment, yet I still get the error code: 
Warning message:
"running command '"C:/Users/ivo19/Anaconda3/lib/R/bin/x64/R" CMD INSTALL -l "C:\Users\ivo19\Anaconda3\Lib\R\library" "../Downloads//thematicmaps_2.1.tar.gz"' had status 1"Warning message in install.packages("../Downloads//thematicmaps_2.1.tar.gz", repos = NULL, :
"installation of package '../Downloads//thematicmaps_2.1.tar.gz' had non-zero exit status"

I hope you can help me with this issue.

**Comment by sbohorquez** [comment]
are you using Russet, or are you doing it in your own pc?

**Comment by IvovanZitteren** [comment]
I am using my own pc

**Comment by sbohorquez** [comment]
Make sure that the package is in the correct location, i.e. right now it tells to search for the folder downloads starting from your current location, try to create a package folder and follow the instructions in #39

**Comment by IvovanZitteren** [comment]
Worked, thank you!
