### ISSUE TITLE
thematicmaps new issue

### ISSUE THREAD

**Issue by Dubbeldip** [janboone/programming-for-economists#48]
Earlier I asked a question about thematicmaps. I followed the instructions in the answer and it worked perfectley well for some time, however now it is suddenly not working again. I did not change anything so i do not understand what happened. I also tried to restart it, but without succes.

Is there a way to solve this?

**Comment by Dubbeldip** [comment]
That is had a non-zero exit status. An error which I had before, but solved by following the steps in #39. However no I am getting it again and I cannot seem to solve it this time.

**Comment by sbohorquez** [comment]
If it is installed already you don't have to reinstall it. If library(thematicmaps) works, you don't have to worry about the install.packages again.

**Comment by Dubbeldip** [comment]
Thats is the thing. It gives me the error again that there is no package again.

**Comment by Dubbeldip** [comment]
It was installed before, but it suddenly gave me the same error again. When I try to install it again, it gives me the same error as before.

**Comment by sbohorquez** [comment]
@misjamikkers Can you help with this one?
