### ISSUE TITLE
Netherlands open map

### ISSUE THREAD

**Issue by DaanWolswijk** [janboone/programming-for-economists#49]
My open map of the Netherlands looks stretched out

**Comment by sbohorquez** [comment]
can you show the code and the result?

**Comment by DaanWolswijk** [comment]
AddMapLayer(MapPlot(), map_municipal) this is the code. I do not know how to show the result

**Comment by sbohorquez** [comment]
take a screenshot

**Comment by DaanWolswijk** [comment]
![image](https://user-images.githubusercontent.com/37589504/41102486-4bacb9e2-6a67-11e8-8942-ded051464622.png)

**Comment by sbohorquez** [comment]
do you get the same results if you try to run the week 6 map?

**Comment by DaanWolswijk** [comment]
No it works there

**Comment by sbohorquez** [comment]
My guess is that when you loaded the data something went wrong. Try copying the code used in week 6, and see if that works.

**Comment by DaanWolswijk** [comment]
It works now thank you!
