### ISSUE TITLE
Error installing conda install -c r ipython-notebook r-irkernel

### ISSUE THREAD

**Issue by BartvanVlijmen** [janboone/programming-for-economists#5]
I'm a EBE student of group 05:

I'm trying to install the r kernel, because in my python the R notebook won't be available, so i can't create a new notebook with R. I thought I could resolve this problem by installing the ipython- notebook R. But I get an error when i try to install this. The error is explained below in the image:

![image](https://cloud.githubusercontent.com/assets/26259183/23849936/a8eb7898-07dd-11e7-9a0b-283843e5685e.png)

If you cant open the image, the error contains the following text:
UnsatisfiableError: The following specifications were found to be in conflict:
- ipython-notebook - ipython 0.13.2 -> python 2.6*
- python 3.6*

How can i resolve this problem?

**Comment by clemensfiedler** [comment]
The problem is that r ipython-notebook wants to install ipython, which requires python 2.6. However, we are using python 3.6. 

Instead install:
`conda install -c r r-essentials`

**Comment by BartvanVlijmen** [comment]
When I try to install this one (which I already tried before) I get another error (error is in the image below). It seems that more students in my class have the same problem, and we were asked to look for a solution on github. We need to create a new notebook with R in jupyter notebook, but for now the only notebook available is Python 3 (image 2)

![image](https://cloud.githubusercontent.com/assets/26259183/23854388/7c94c862-07f1-11e7-8763-dc7b2ef14b17.png)

![image](https://cloud.githubusercontent.com/assets/26259183/23854445/d5baff06-07f1-11e7-80b7-eed6da687533.png)

**Comment by clemensfiedler** [comment]
Have you tried to reinstall [anaconda](https://www.continuum.io/downloads), then running the installation command for 'r-essentials' again?
