### ISSUE TITLE
2A map download

### ISSUE THREAD

**Issue by marcelhv99** [janboone/programming-for-economists#51]
For me the download of the municipal map with the following code gives the error:

map_municipal <- read.csv2("../Sourcedata/nld_municipal_map.csv", stringsAsFactors = FALSE, dec = ".")
head(map_municipal)

Warning message in file(file, "rt"):
"cannot open file '../Sourcedata/nld_municipal_map.csv': No such file or directory"

This whilst I have a file located there and this file does open in the old practice from week 6 about maps.

How can I solve this?

**Comment by marcelhv99** [comment]
The same problem occurs with 2C.

**Comment by marcelhv99** [comment]
![image](https://user-images.githubusercontent.com/37869566/41101658-0b523298-6a65-11e8-8595-643dcd8dc8de.png)

**Comment by sbohorquez** [comment]
Do you have a sourcedata folder created in the same way as in week 6 for this assignment?, if not then follow the same organization for the files as the one shown in week 6

**Comment by marcelhv99** [comment]
I have put it in the same sourcedata folder and it even works in the old file, just not in the exam file.

**Comment by marcelhv99** [comment]
I also tried to rerun the kernel, which also had no effect

**Comment by marcelhv99** [comment]
I have organized it exactly the same way now, which doesn't solve the problem.

**Comment by sbohorquez** [comment]
then put your exam file and map file in the same folder and run:

map_municipal <- read.csv2("nld_municipal_map.csv", stringsAsFactors = FALSE, dec = ".")

**Comment by marcelhv99** [comment]
I redownloaded and restarted making the exam and then it dowloaded without problems, thanks for the help!
