### ISSUE TITLE
Thematic maps

### ISSUE THREAD

**Issue by FlorisvdHeijden** [janboone/programming-for-economists#52]
i get this error when installing thematicmaps
Warning message:
"running command '"C:/Users/Floris/Anaconda3/lib/R/bin/x64/R" CMD INSTALL -l "C:\Users\Floris\Anaconda3\Lib\R\library" "../Package//thematicmaps_2.1.tar.gz"' had status 1"Warning message in install.packages("../Package//thematicmaps_2.1.tar.gz", repos = NULL, :
"installation of package '../Package//thematicmaps_2.1.tar.gz' had non-zero exit status"
Error in library(thematicmaps): there is no package called 'thematicmaps'
Traceback:

1. library(thematicmaps)
2. stop(txt, domain = NA)

these are the commands im using
install.packages("../Package//thematicmaps_2.1.tar.gz", repos = NULL, type = "source")
library(thematicmaps)
library(tidyverse)

i have 2 folders on the same level desktop/Package and desktop/Code
in code the notebook is saved
in package the zip file

the anaconda prompt gives this
In R CMD INSTALL
ERROR: dependencies 'maptools', 'rgdal', 'rgeos' are not available for package 'thematicmaps'
* removing 'C:/Users/Floris/Anaconda3/Lib/R/library/thematicmaps'

what can i do to fix this?

**Comment by clemensfiedler** [comment]
try running:
```
install.packages(c("maptools", 'rgdal','rgeos'))
install.packages("../Package//thematicmaps_2.1.tar.gz", repos = NULL, type = "source")
```

you might have to restart the notebook for this and specify a repository

**Comment by FlorisvdHeijden** [comment]
thanks this seems to have worked
