### ISSUE TITLE
could not find gvlma package

### ISSUE THREAD

**Issue by JurreSpit** [janboone/programming-for-economists#53]
I can open the gvlma package, but at 1b he can't find the package

**Comment by clemensfiedler** [comment]
with opening you mean 
```R
library(gvlma)
```

**Comment by JurreSpit** [comment]
this came after I opened it:
package 'gvlma' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\jurre\AppData\Local\Temp\RtmpohvMci\downloaded_packages

**Comment by clemensfiedler** [comment]
'package 'gvlma' successfully unpacked and MD5 sums checked' appears after the command
```
install.packages('gvlma')
```
but you also need to open it with 

```
library(gvlma)
```

**Comment by JurreSpit** [comment]
it worked, thanks!
