### ISSUE TITLE
2D

### ISSUE THREAD

**Issue by legokip** [janboone/programming-for-economists#54]
When trying to use substr, it always gives as output 'c(1,'. However, i cannot find this data in the dataframe, and don't know how to fix it?

**Comment by sbohorquez** [comment]
can you add the code you're using?

**Comment by legokip** [comment]
i'm using the following code
schools1 <- schools 
substr(schools1['POSTCODE'], start =1, stop =4) -> PC4 
PC4

**Comment by sbohorquez** [comment]
look at the commands mutate and select used in the week 5, 6 and 7 codes.
