### ISSUE TITLE
R assignment 2

### ISSUE THREAD

**Issue by marcelhv99** [janboone/programming-for-economists#55]
After I solved the problem of reading the map, it is now impossible to download download the thematicmaps library, which is needed for the AddMapLayer function. How can I solve this?

**Comment by sbohorquez** [comment]
Follow the instruction in #39 or use the Russet server.

**Comment by marcelhv99** [comment]
I followed the instructions in #39, but it still gives the following error:




Warning message:
"running command '"C:/Users/Gebruiker/Anaconda3/lib/R/bin/x64/R" CMD INSTALL -l "C:\Users\Gebruiker\Anaconda3\Lib\R\library" "../Package//thematicmaps_2.1.tar.gz"' had status 1"Warning message in install.packages("../Package//thematicmaps_2.1.tar.gz", repos = NULL, :
"installation of package '../Package//thematicmaps_2.1.tar.gz' had non-zero exit status

**Comment by sbohorquez** [comment]
try #52

**Comment by marcelhv99** [comment]
That worked, thanks!
