### ISSUE TITLE
uploading packages

### ISSUE THREAD

**Issue by nicvdv** [janboone/programming-for-economists#56]
i get an error every time i try to upload my packages in the R assignement
i create a new cell with : install.packages('gvlma', repos='http://cran.us.r-project.org')
what am i doing wrong here? how can i get the packages on board as i should in R?

**Comment by nicvdv** [comment]
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
Warning message in install.packages("gvlma", repos = "http://cran.us.r-project.org"):
"'lib = "/usr/local/lib/R/site-library"' is not writable"
Error in install.packages("gvlma", repos = "http://cran.us.r-project.org"): unable to install packages
Traceback:

1. install.packages("gvlma", repos = "http://cran.us.r-project.org")
2. stop("unable to install packages")

**Comment by sbohorquez** [comment]
If you're using Russet there's no need to install the packages, they are already installed on the server.

**Comment by nicvdv** [comment]
i am using russet. but if i enter in question 1a 
ggplot(data = df1, aes(x = group, y = V1)) +
    geom_boxplot()
i get this error
Error in eval(expr, envir, enclos): could not find function "ggplot"
Traceback:
so there must be something im doing wrong?

**Comment by sbohorquez** [comment]
Did you run library(tidyverse) and library(gvlma)?

**Comment by nicvdv** [comment]
Im the biggest idiot ever. thanks
