### ISSUE TITLE
the maps package

### ISSUE THREAD

**Issue by JurreSpit** [janboone/programming-for-economists#58]
when I try to install thematicmaps package there comes:
Warning message:
"running command '"C:/Users/jurre/Anaconda3/lib/R/bin/x64/R" CMD INSTALL -l "C:\Users\jurre\Anaconda3\Lib\R\library" "../Package//thematicmaps_2.1.tar.gz"' had status 1"Warning message in install.packages("../Package//thematicmaps_2.1.tar.gz", repos = NULL, :
"installation of package '../Package//thematicmaps_2.1.tar.gz' had non-zero exit status"

what do I need to do?

**Comment by clemensfiedler** [comment]
Can you try this:
https://github.com/janboone/programming-for-economists/issues/52

**Comment by JurreSpit** [comment]
it does unpack maptools,rdgal and rgeos.
but I still get the same message.

**Comment by JurreSpit** [comment]
but it does work on the laptop of my collaborator, is it fine if I fork it from him?

**Comment by janboone** [comment]
if you work together, this is fine. make sure that both of you upload the exams on your github page and add the links to the google form.
