### ISSUE TITLE
Issue downloading/opening this notebook for the assignments

### ISSUE THREAD

**Issue by BartvanVlijmen** [janboone/programming-for-economists#6]
Im a EBE student of group 05:

I can't seem to open or download the notebooks for the assignments. If I try to download the notebook a get a pop-up which lets me select the option in which program I want to open this file. But in neither one the file opens correctly. In which program would this file normally be opened?

**Comment by clemensfiedler** [comment]
Are you using Windows or Mac?

Windows:
You have to save the notebook somewhere on your computer. (for example in the downloads folder).
Then open this folder in the file explorer and press Bestand (file) in the top right corner and opdrachtpromp. A black window will open. Type 'jupyter notebook' and open the notebook.

**Comment by BartvanVlijmen** [comment]
Thank you, it works now.
