### ISSUE TITLE
Final Exam Grade

### ISSUE THREAD

**Issue by jurmaaas** [janboone/programming-for-economists#70]
Dear Teachers,

I have made the final assignment and handed it in on time, but haven't gotten my grade. I forgot to fill in the google format on the day of the exam, so i've filled in the google format last week. 
I hope i'm not too late, and that I can still receive my grade! 

Kind regards

Jur Maas 2011217 , u748506 , EBE-03

**Comment by janboone** [comment]
Indeed you are on the list. We will grade your assignment together with the resit. So, you will receive your grade!

**Comment by jurmaaas** [comment]
Dear Mr Boone,

Than how do I know if I have to make the resit exam?

Kind Regards

Jur Maas 2011217 u748506

Op ma 25 jun. 2018 om 13:52 schreef jan boone <notifications@github.com>
