### ISSUE TITLE
Wrong repository link

### ISSUE THREAD

**Issue by SamHamers** [janboone/programming-for-economists#73]
Today I signed up for the exam on the 7th of september. Only I linked my original Github repository (.../SamHamers/Assignments). Later I read that we were supposed to make a new repository for the exam. Can I upload the exam in the Assignments repository or can you change the specified link in the Google form to the new repository: .../SamHamers/exam_sep_7?

**Comment by janboone** [comment]
Uploading in your Assignments-repos. is fine as long as we can clearly see what your exam is.
