### ISSUE TITLE
Thematiccs package not working

### ISSUE THREAD

**Issue by RoHaNc112** [janboone/programming-for-economists#75]
I had previously installed the package 'thematicmaps' for the course - Programming for Economists. It was working properly throughout the course and I could even use it during the final exam(which has been cancelled).

However, when I started practicing for the exam again, I could not install the package. I thought that the package is already installed from before so I only called it with the command - library( 'thematicmaps' ) however, its showing that the package does not exist. When I'm installing it, its showing this error - 

Installing package into 'C:/Users/rohan/Documents/R/win-library/3.5'
(as 'lib' is unspecified)
Warning message in install.packages("../Downloads//thematicmaps_2.1.tar.gz", repos = NULL, :
"installation of package '../Downloads//thematicmaps_2.1.tar.gz' had non-zero exit status"

This is the code I used - 

install.packages("../Downloads//thematicmaps_2.1.tar.gz", repos = NULL, type = "source") 

In place of Packages in the above code, I put Downloads as the zip file lies there. In addition, that is how I had installed it earlier. I also tried changing the type to 'windows.binary'

I did all the above on Jupyter notebook and am using windows 10

**Comment by misjamikkers** [comment]
The “non-zero exit status” is unfortunately non-informative error statement which the computer gives as something goes wrong. You can email me about an appointment on Wednesday’s if want to try to install the package. You do not need the package for the exams in September. I will post this information on blackboard as well.
