### ISSUE TITLE
Downloading packages

### ISSUE THREAD

**Issue by fleurdeloijer** [janboone/programming-for-economists#78]
While downloading packages I got this message:
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()

I think this is also why the function %>% does not work, which I think I do need…
How do I solve this?

**Comment by misjamikkers** [comment]
You indeed need the pipe operator %>%.  However, the message you show is a ‘normal’ warning that shows up when you load tidyverse and has nothing to do with your problem. 

What is the message when you use the pipe operator?

**Comment by misjamikkers** [comment]
The warning you showed just indicates that some commands (e.g. filter and lag) are also used by other packages.

**Comment by fleurdeloijer** [comment]
I have already found my mistake, thanks anyways!
