### ISSUE TITLE
R

### ISSUE THREAD

**Issue by bartvanvlerken** [janboone/programming-for-economists#80]
Ik krijg de factorvariables niet omgezet naar numeric variables, maar ik doe precies wat er staat op deze site? https://www.dummies.com/programming/r/how-to-convert-a-factor-in-r/

**Comment by misjamikkers** [comment]
In the course we did it a bit different:
More like 
Df$var <- as.numeric(as.character(Df$var))
See e.g.
https://stackoverflow.com/questions/27528907/how-to-convert-data-frame-column-from-factor-to-numeric/27528953

Does this work?

**Comment by bartvanvlerken** [comment]
Yes, thank you!
