### ISSUE TITLE
Videos about R

### ISSUE THREAD

**Issue by Royvdk** [janboone/programming-for-economists#82]
I am not able to open the last two videos about the R exams. The video doesn't load and only gives a lock image.

**Comment by misjamikkers** [comment]
For the R videos, you need to be either on campus or you need to use your vpn (using a Cisco client)

**Comment by Royvdk** [comment]
I am at the university, but it still doesn't work

**Comment by misjamikkers** [comment]
It works for me after I signed in on the page with the lock image (top right). Does that work for you?

**Comment by Royvdk** [comment]
I have logged in, on Chrome and in Explorer, but they both didn't work

**Comment by misjamikkers** [comment]
Did you sign in on black board, used the link to the videos and then pressed sign in on the top right page of the video?

**Comment by Royvdk** [comment]
Yes, I have done this a few times and I still have the lock image as you can see on the image

![image](https://user-images.githubusercontent.com/37621616/45596704-4c507200-b9c0-11e8-822b-8e19945d0b60.png)

**Comment by misjamikkers** [comment]
which email address do you use to log in?

**Comment by misjamikkers** [comment]
pls send your email address by mail to m.c.mikkers@uvt.nl

**Comment by misjamikkers** [comment]
Problem solved by changing settings.
