### ISSUE TITLE
Explaining Code

### ISSUE THREAD

**Issue by BornaMD** [janboone/programming-for-economists#83]
During the exam in June, I thought we needed to explain all of the code we used and why we did so. Thus this is what I did. What I mean by this is for example in Python 1c):

> #### Explanation: 
> The dataframe contains data on the cost level of the merged firm, the output level of firm 1 and the output level of firm 2. These are named respectively: c_merged_firm, output_non_merging_firm and output_merged_firm. `pd.DataFrame()` is used to make a dataframe; `df_after_merger`. After which I used `df_after_merger.head()` to inspect the dataframe.

When looking at the python notebook exam answers (the one that was linked to in the announcements on BB), this was not done. 
My question therefor is: Do we need to explain our code and code-use in the coming exam (21 September)? 

Greetings,
Borná

**Comment by BornaMD** [comment]
An extra example:

> #### Explanation: 
> `plt.hist(x=df_after_merger['P'],)` is what creates the histogram of `P`.  
> `vlines()` is used to create a vertical line in `P0 = 0.475`.  
> `plt.legend()` is the code for the legend.   
> `plt.xlabel()` and `plt.ylabel()` name the labels.  
> `plt.xticks(np.arange(.43, .53, .01))` makes sure the histogram is readable.   
> `plt.title()`for the title.  
> `plt.show()` shows the graph.

**Comment by janboone** [comment]
Indeed, if you explain your code like this, this is fine.

**Comment by BornaMD** [comment]
So we do need to explain every code we use?
