### ISSUE TITLE
Installing packages

### ISSUE THREAD

**Issue by BornaMD** [janboone/programming-for-economists#85]
When I try to install packages I get the following result in the prompt:

> C:\WINDOWS\system32>conda install -c r r-essentials
> Solving environment: failed
> 
> CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/r/noarch/repodata.json>
> Elapsed: 00:00.195401
> CF-RAY: 45d47b94086e9d32-AMS
> 
> The remote server could not find the noarch directory for the
> requested channel with url: https://conda.anaconda.org/r
> 
> As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
> associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
> empty. please request that the channel administrator create
> `noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
> $ mkdir noarch
> $ echo '{}' > noarch/repodata.json
> $ bzip2 -k noarch/repodata.json
> 
> You will need to adjust your conda configuration to proceed.
> Use `conda config --show channels` to view your configuration's current state.
> Further configuration help can be found at <https://conda.io/docs/config.html>.
> 
> 
> 
> C:\WINDOWS\system32>
> 
How do I solve this?

**Comment by janboone** [comment]
use the russet server from your laptop. See http://janboone.github.io/programming-for-economists/install.html
