### ISSUE TITLE
exam 21 september

### ISSUE THREAD

**Issue by PietSteeghs** [janboone/programming-for-economists#86]
when i want to download the assignments from blackboard, it loads the files on a new page instead of downloading it, so i can't open them on my russet server

**Comment by janboone** [comment]
Did you right click on the assignment and then use "save link as"?

If this does not work, use another browser (like chrome) to download the files.

**Comment by PietSteeghs** [comment]
>           Did you right click on the assignment and then use "save link as"?
> If this does not work, use another browser (like chrome) to download the files.

thankyou
