### ISSUE TITLE
Opening R

### ISSUE THREAD

**Issue by Luuk1998** [janboone/programming-for-economists#88]
I can't open R neither in jupyter nor in Rstudio in the right way

**Comment by misjamikkers** [comment]
Did R work when you prepared the exam?

**Comment by Luuk1998** [comment]
Yes

**Comment by misjamikkers** [comment]
If you don’t give more specific information, i can’t figure out what is wrong. Can you switch to the russet server?

**Comment by Luuk1998** [comment]
What's the russet server?

**Comment by janboone** [comment]
https://russet.uvt.nl/

**Comment by misjamikkers** [comment]
You can log in with your TiU credentials. With this jupyter hub you can work both with R and python.

**Comment by misjamikkers** [comment]
If you work in Jupyter on the russet server you should open exam exam_2_student.ipynb
Did you open this file?

**Comment by Luuk1998** [comment]
I just opened the 4 files that were in the assignment, where can I find that one?

**Comment by misjamikkers** [comment]
In the assignment on blackboard.

**Comment by Luuk1998** [comment]
Yes that one is working
