### ISSUE TITLE
Question about registration at Datacamp

### ISSUE THREAD

**Issue by SuzannePluym** [janboone/programming-for-economists#9]
Hello,

I am a EBE student from group 1EBE-01. An announcement was posted on Blackboard this afternoon showing who are not registered at Datacamp. My name is on that list, but with a wrong e-mail address. I did register for Datacamp, but with my Tilburg University e-mail address. I would like to know if this is a problem and if so, how I should solve this.
Also, I didn't receive the email from Datacamp that allows me to view their premium content. How can I solve this?

Thank you in advance.

**Comment by janboone** [comment]
we used the email address that you gave in the google form. Can you email me your uvt email address?

**Comment by SuzannePluym** [comment]
I already filled in the Google Form again when I saw my email adress wasn't correct. Does this mean that the problem is solved now?
