### ISSUE TITLE
When I type in functions such as head() into R, it does not give me any return

### ISSUE THREAD

**Issue by DaanWolswijk** [janboone/programming-for-economists#90]

**Comment by misjamikkers** [comment]
Did you put the name of the data frame between the brackets?

**Comment by DaanWolswijk** [comment]
yes

**Comment by misjamikkers** [comment]
Could you send the exact code?

**Comment by DaanWolswijk** [comment]
![image](https://user-images.githubusercontent.com/37589504/45884273-cc594c00-bdb3-11e8-9979-b2dcd4298bf6.png)

**Comment by misjamikkers** [comment]
Please look carefully at your code.
You should read in the csv file. Then you should be able to use str() and head()
The thing you did wrong was in creating the variable. Please dplyr to the create the new variable.

**Comment by misjamikkers** [comment]
Hint: when you read in the data look at the separator
