### ISSUE TITLE
Kernel keeps dying when plotting histogram in python

### ISSUE THREAD

**Issue by willemvdm** [janboone/programming-for-economists#92]
Currently working on e from the python assignment in the russet server. When i try to plot the histogram. The kernel dies and has to restart. Trying again all code runs fine until the histogram part. There the kernel dies again and has to restart, stopping me from continuing the exam.

**Comment by janboone** [comment]
what is your u-number?

**Comment by willemvdm** [comment]
u800370
2014236

**Comment by janboone** [comment]
I will look into your notebook for a second

**Comment by willemvdm** [comment]
Fully restarting the russet server has solved it for now :)

**Comment by janboone** [comment]
you got an error as the server works with a different version of matplotlib.

Use normed=True (instead of density=True)
