### ISSUE TITLE
error melding

### ISSUE THREAD

**Issue by Pascalevdven** [janboone/programming-for-economists#93]
Medicaid %>%
mutate(Cost_per_Recipient = Total_costs / Recipients )
head(Medicaid)

I made this. Then in the next question i begin with this:

ggplot(Medicaid, aes(x = Year, y = Cost_per_Recipient)) +  geom_line() 

Then I get the message that Cost_per_Recipient is not found

**Comment by misjamikkers** [comment]
Could you send a screenshot of the above code?

**Comment by Pascalevdven** [comment]
>           Could you send a screenshot of the above code?

![naamloos](https://user-images.githubusercontent.com/37653960/45885727-7b4b5700-bdb7-11e8-8b3a-fd78dd758c3b.png)
![naamloos2](https://user-images.githubusercontent.com/37653960/45885733-7f777480-bdb7-11e8-8c41-11a652037fa0.png)

**Comment by misjamikkers** [comment]
Is Cost_per_Recipient a numeric?
