### ISSUE TITLE
r read function doesnt work

### ISSUE THREAD

**Issue by uberka** [janboone/programming-for-economists#94]
The file is at the indicated directory but R doesn't see it.
Error: '../Downloads/exam/Medicaid.csv' does not exist in current working directory ('C:/Users/Usame/Downloads/exam').
Traceback:

1. read_csv("../Downloads/exam/Medicaid.csv")
2. read_delimited(file, tokenizer, col_names = col_names, col_types = col_types, 
 .     locale = locale, skip = skip, comment = comment, n_max = n_max, 
 .     guess_max = guess_max, progress = progress)
3. standardise_path(file)
4. check_path(path)
5. stop("'", path, "' does not exist", if (!is_absolute_path(path)) paste0(" in current working directory ('", 
 .     getwd(), "')"), ".", call. = FALSE)

**Comment by misjamikkers** [comment]
Did you use read.csv2()?

**Comment by janboone** [comment]
are you working on the russet server or on your laptop?

**Comment by uberka** [comment]
laptop
i solved the problem thank u for ur quick reponse
