### ISSUE TITLE
scatter plot

### ISSUE THREAD

**Issue by Mcococh** [janboone/programming-for-economists#96]
i plotted scatter plot but it doesnt give me any dots -pyhton
plt.figure()
plt.plot(x='y',y='z', kind = 'scatter')
plt.xlabel = ('$y$')
plt.ylabel = ('$z$')
plt.show()

**Comment by janboone** [comment]
I have not the full code, but what does x='y' mean? Presumably y comes from a dataframe?

**Comment by janboone** [comment]
but 'y' is a string in the matplotlib command that you use. Or do you want to use pandas to plot? Then the statement should not start with plt...
