### ISSUE TITLE
read.csv

### ISSUE THREAD

**Issue by Niels213** [janboone/programming-for-economists#97]
When i try to open the Medicaid.csv file i get this error.
Error in inherits(x, "connection"): object 'Medicaid.csv' not found
Traceback:

1. read_csv(Medicaid.csv)
2. read_delimited(file, tokenizer, col_names = col_names, col_types = col_types, 
 .     locale = locale, skip = skip, comment = comment, n_max = n_max, 
 .     guess_max = guess_max, progress = progress)
3. source_name(file)
4. is.connection(x)
5. inherits(x, "connection")

**Comment by misjamikkers** [comment]
1. Please use read.csv2
2. Use “ “ around the path, see e.g. 
http://rprogramming.net/read-csv-in-r/
3. You have to specify where R should find your csv file
