### ISSUE TITLE
Numeric variable

### ISSUE THREAD

**Issue by Royvdk** [janboone/programming-for-economists#98]
When I do this: is.numeric(mydata$Year..Recipients.Total_costs) the answer is TRUE. But if I wanted to gut further the error non-numeric argument to binary operator occurs

**Comment by misjamikkers** [comment]
Use str() to check the structure.
And change the variable if needed

**Comment by Royvdk** [comment]
Now I get this, but I still get the error: non-numeric argument to binary operator
Data.frame':	13 obs. of  2 variables:
 $ Year..Recipients.Total_costs: num  1 2 3 4 5 6 7 8 9 10 ...
 $ Year                        : num  1 2 3 4 5 6 7 8 9 10 ...
>

**Comment by Royvdk** [comment]
If I mutate it, it still doesn't work

mutate(Year..Recipients.Total_costs = as.numeric(as.character(Year..Recipients.Total_costs)))
Error in mutate(Year..Recipients.Total_costs = as.numeric(as.character(Year..Recipients.Total_costs))) : 
  object 'Year..Recipients.Total_costs' not found
