### ISSUE TITLE
Error in read.csv

### ISSUE THREAD

**Issue by Siemenvda** [janboone/programming-for-economists#99]
When in try to read in Medicaid.csv like this: read.csv2("../Exam/Sourcedata/Medicaid.csv")
I get this error: 
Warning message in file(file, "rt"):
"cannot open file '..Exam/Sourcedata/Medicaid.csv': No such file or directory"

Error in file(file, "rt"): cannot open the connection
Traceback:

1. read.csv2("..Exam/Sourcedata/Medicaid.csv")
2. read.table(file = file, header = header, sep = sep, quote = quote, 
 .     dec = dec, fill = fill, comment.char = comment.char, ...)
3. file(file, "rt")

**Comment by misjamikkers** [comment]
Check if the file is folder you specify in the command

**Comment by misjamikkers** [comment]
And where you save the code: You tell R to go one folder up, then go down to the folder exam etc

**Comment by Siemenvda** [comment]
Yes, the file is in Sourcedata and Sourcedata is located under Exam

**Comment by misjamikkers** [comment]
And where is your code stored?

**Comment by Siemenvda** [comment]
I think it worked, thanks
